"""Initial migration

Revision ID: 4669dc1c02ed
Revises: 
Create Date: 2024-12-25 18:39:06.646565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4669dc1c02ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',

    )
    # ### end Alembic commands ###
